#!/usr/bin/env python
import sys, os

try:
    from waflib.extras import symwaf2ic
    from waflib.extras.gtest import summary
    recurse = lambda *args, **kwargs: None
except ImportError:
    from gtest import summary
    from symwaf2ic import recurse_depends
    recurse = lambda ctx: recurse_depends(depends, ctx)

def depends(ctx):
    ctx('vmodule')

def options(opt):
    recurse(opt)
    opt.load('compiler_cxx')
    opt.load('gtest')

def configure(cfg):
    recurse(cfg)
    cfg.load('compiler_cxx')
    cfg.load('gtest')

def build(bld):
    recurse(bld)

    bld(target          = 'vmodule-test',
        features        = 'cxx cxxprogram gtest',
        source          = bld.path.ant_glob('*.cpp'),
        install_path    = os.path.join('bin', 'tests'),
        use             = [ 'vmodule_objects' ],
    )
